language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

#env:
  #matrix:
    #- LOWEST_DEPS=""
    #- LOWEST_DEPS="--prefer-lowest"

#services:
#  - mysql
#  - postgres

sudo: false

before_script:
  - for app in activesync tracker projectmanager bookmarks news_admin registration phpbrain wiki sambaadmin sitemgr phpfreechat ; do git clone https://github.com/EGroupware/$app.git ; done
  - svn -q checkout https://svn.code.sf.net/p/adldap/code/trunk/src phpgwapi/inc/adldap

script:
  - ./doc/php_syntax_check.sh

cache:
  directories:
    - $HOME/.composer/cache
