language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

#env:
  #matrix:
    #- LOWEST_DEPS=""
    #- LOWEST_DEPS="--prefer-lowest"

#services:
#  - mysql
#  - postgres

sudo: required
dist: trusty

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y myrepos
  - mr --trust-all --stats up

script:
  - ./doc/php_syntax_check.sh
  #- ./vendor/bin/sabre-cs-fixer fix . --dry-run --diff

cache:
  directories:
    - $HOME/.composer/cache
