language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

#env:
  #matrix:
    #- LOWEST_DEPS=""
    #- LOWEST_DEPS="--prefer-lowest"

#services:
#  - mysql
#  - postgres

sudo: required
dist: trusty
# this myy fix hhvm builds according to https://docs.travis-ci.com/user/languages/php#HHVM-versions-on-Trusty
group: edge

before_script:
  # - mysql -e 'create database egroupware'
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  #- composer update --prefer-source $LOWEST_DEPS
  - sudo apt-get update -qq
  - sudo apt-get install -y myrepos
  - mr --trust-all --stats up

script:
  ./doc/php_syntax_check.sh
  ./doc/test-cli.php

cache:
  directories:
    - $HOME/.composer/cache